clc;clearvars;close all;
A=imread('peppers.png');
%A = rgb2gray(A);
I=double(A)/255;
R=I(:,:,1);
G=I(:,:,2);
B=I(:,:,3); 
K = min(1-I,[],3);
denom = 1-K+eps;
C = (1-R-K)./denom;
M = (1-G-K)./denom;
Y = (1-B-K)./denom;
CMYK = zeros(384,512,4);
CMYK(:,:,1)= C;
CMYK(:,:,2)= M;
CMYK(:,:,3)= Y;
CMYK(:,:,4)= K;
subplot(3,4,1);imhist(C);title('C of original image');
subplot(3,4,2);imhist(M);title('M of original image');
subplot(3,4,3);imhist(M);title('Y of original image');
subplot(3,4,4);imhist(K);title('K of original image');
C_eq = histeq(C);
M_eq = histeq(M);
Y_eq = histeq(Y);
K_eq = histeq(K);
subplot(3,4,5);imhist(C_eq);title('C equalised');
subplot(3,4,6);imhist(M_eq);title('M equalised');
subplot(3,4,7);imhist(Y_eq);title('Y equalised');
subplot(3,4,8);imhist(K_eq);title('K equalised');
CMYK_eq = zeros(384,512,4);
CMYK_eq(:,:,1)= C_eq;
CMYK_eq(:,:,2)= M_eq;
CMYK_eq(:,:,3)= Y_eq;
CMYK_eq(:,:,4)= K_eq;
inprof = iccread('USSheetfedCoated.icc');
outprof = iccread('sRGB.icm');
Cmask = makecform('icc',inprof,outprof);
I_rgb = applycform(CMYK,Cmask);
I_rgb_eq = applycform(CMYK_eq,Cmask);
subplot(3,4,10);imshow(I_rgb,[]);title('original CMYK image');
subplot(3,4,11);imshow(I_rgb_eq,[]);title('CMYK image equalised ');

